name: Cron Job
on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode
        uses: actions/checkout@v1
      
      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python3 my_script.py

